/**
 * Convert chrome.cookies.Cookie[] to Netscape cookies.txt format.
 * Tab-separated 7 fields per row:
 *   domain  include_subdomains  path  secure  expires  name  value
 *
 * `expires=0` for session cookies (yt-dlp + transcript-api both tolerate).
 * Values are emitted as-is (chrome.cookies API returns them URL-decoded
 * already; yt-dlp doesn't expect re-encoding).
 */
export function cookiesToNetscape(cookies) {
  const header = [
    '# Netscape HTTP Cookie File',
    '# Generated by AFFiNE Capture extension',
    '# Do not edit manually — overwritten on next sync',
    '',
  ];
  const rows = cookies.map(c => {
    const includeSubdomains = c.domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const secure = c.secure ? 'TRUE' : 'FALSE';
    const expires = c.session ? '0' : Math.floor(c.expirationDate || 0);
    return [
      c.domain, includeSubdomains, c.path, secure, String(expires), c.name, c.value,
    ].join('\t');
  });
  return header.concat(rows).join('\n') + '\n';
}
