/**
 * Affine YT Cookie Sync — background service worker (MV3).
 *
 * Reads the user's YouTube cookies via the chrome.cookies API, formats
 * them as a Netscape cookies.txt, and POSTs to the configured Affine
 * ingest endpoint. Triggers:
 *
 *   - chrome.runtime.onInstalled  → first sync after install
 *   - chrome.cookies.onChanged    → debounced sync on any YT cookie change
 *   - chrome.alarms (daily-sync)  → safety net, every 24h
 *   - chrome.runtime.onMessage    → manual "Sync now" button from popup
 *
 * Service workers in MV3 die after ~30s idle, so we use chrome.alarms
 * for the debounce (survives worker death) rather than setTimeout.
 */

const ALARM_DAILY_SYNC = 'yt-cookie-daily-sync';
const ALARM_DEBOUNCE_SYNC = 'yt-cookie-debounce-sync';
const DEBOUNCE_MINUTES = 0.5;  // 30s

// ── Cookie collection ──────────────────────────────────────────────

/**
 * Fetch all YouTube cookies via chrome.cookies API. Returns the
 * deduplicated list across both `youtube.com` and `.youtube.com` scopes.
 * httpOnly cookies ARE included — they're inaccessible from page JS but
 * the chrome.cookies API has full access (that's the whole point of
 * this extension).
 */
async function collectYouTubeCookies() {
  const [bare, dotted] = await Promise.all([
    chrome.cookies.getAll({ domain: 'youtube.com' }),
    chrome.cookies.getAll({ domain: '.youtube.com' }),
  ]);
  const seen = new Set();
  const out = [];
  for (const c of [...bare, ...dotted]) {
    const key = `${c.name}|${c.domain}|${c.path}`;
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(c);
  }
  return out;
}

/**
 * Convert chrome.cookies.Cookie[] to Netscape cookies.txt format.
 * Tab-separated 7 fields per row:
 *   domain  include_subdomains  path  secure  expires  name  value
 *
 * `expires=0` for session cookies (yt-dlp + transcript-api both tolerate).
 * Values are emitted as-is (chrome.cookies API returns them URL-decoded
 * already; yt-dlp doesn't expect re-encoding).
 */
function cookiesToNetscape(cookies) {
  const header = [
    '# Netscape HTTP Cookie File',
    '# Generated by Affine YT Cookie Sync extension',
    '# Do not edit manually — overwritten on next sync',
    '',
  ];
  const rows = cookies.map(c => {
    const includeSubdomains = c.domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const secure = c.secure ? 'TRUE' : 'FALSE';
    const expires = c.session ? '0' : Math.floor(c.expirationDate || 0);
    return [
      c.domain,
      includeSubdomains,
      c.path,
      secure,
      String(expires),
      c.name,
      c.value,
    ].join('\t');
  });
  return header.concat(rows).join('\n') + '\n';
}

// ── Sync ───────────────────────────────────────────────────────────

/**
 * The full sync flow: read config → collect cookies → POST to ingest.
 * Persists the last-sync result to chrome.storage.local so the popup
 * can render status without re-running the sync.
 */
async function syncCookies() {
  const { ingestUrl, ingestToken } = await chrome.storage.local.get(
    ['ingestUrl', 'ingestToken'],
  );
  if (!ingestUrl || !ingestToken) {
    const result = { ok: false, error: 'not configured', synced_at: null };
    await chrome.storage.local.set({ lastSync: result });
    return result;
  }

  let cookies;
  try {
    cookies = await collectYouTubeCookies();
  } catch (e) {
    const result = { ok: false, error: `collect failed: ${e?.message ?? e}`, synced_at: null };
    await chrome.storage.local.set({ lastSync: result });
    return result;
  }

  if (cookies.length === 0) {
    const result = { ok: false, error: 'no YouTube cookies — log into YouTube first', synced_at: null };
    await chrome.storage.local.set({ lastSync: result });
    return result;
  }

  const body = cookiesToNetscape(cookies);
  const endpoint = `${ingestUrl.replace(/\/$/, '')}/youtube/cookies`;
  let resp;
  try {
    resp = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${ingestToken}`,
        'Content-Type': 'text/plain',
      },
      body,
    });
  } catch (e) {
    const result = { ok: false, error: `network: ${e?.message ?? e}`, synced_at: null };
    await chrome.storage.local.set({ lastSync: result });
    return result;
  }

  const result = {
    ok: resp.ok,
    status: resp.status,
    cookie_count: cookies.length,
    byte_count: body.length,
    synced_at: new Date().toISOString(),
    error: resp.ok ? null : `HTTP ${resp.status}`,
  };
  await chrome.storage.local.set({ lastSync: result });
  return result;
}

// ── Triggers ───────────────────────────────────────────────────────

chrome.runtime.onInstalled.addListener(() => {
  // First sync on install (no-op if not yet configured).
  syncCookies();
  // Schedule the daily safety-net.
  chrome.alarms.create(ALARM_DAILY_SYNC, { periodInMinutes: 60 * 24 });
});

chrome.cookies.onChanged.addListener(({ cookie }) => {
  if (!cookie?.domain?.includes('youtube.com')) return;
  // Debounce: replace any pending alarm with a fresh one.
  chrome.alarms.create(ALARM_DEBOUNCE_SYNC, { delayInMinutes: DEBOUNCE_MINUTES });
});

chrome.alarms.onAlarm.addListener(alarm => {
  if (alarm.name === ALARM_DAILY_SYNC || alarm.name === ALARM_DEBOUNCE_SYNC) {
    syncCookies();
  }
});

chrome.runtime.onMessage.addListener((msg, _sender, sendResponse) => {
  if (msg?.type === 'sync-now') {
    syncCookies().then(sendResponse);
    return true;  // keep the channel open for the async response
  }
  if (msg?.type === 'get-last-sync') {
    chrome.storage.local.get('lastSync').then(({ lastSync }) => {
      sendResponse(lastSync ?? null);
    });
    return true;
  }
});
